### ISSUE TITLE
Dependencies of the gstlearn python package

### ISSUE THREAD

**Issue by nicolas-clausolles** [gstlearn/gstlearn#442]
Currently, the package declares dependencies to the following libraries: numpy, scipy, pandas, matplotlib, plotly. Although they are all useful for "scripting" applications, we only require a few of them when using gstlearn as a computational library.

It would be nice to have a "core" gstlearn package that comes with only a restricted set of "computational" dependencies, and to declare the others as optional configurations in the pyproject.toml.

At first sight, for the core dependencies, I would say:
- numpy: required
- pandas: unsure, it is used a few times in `pygstlearn.i`, so it could be kept for now
- scipy: not needed. It is used only once in `pygstlearn.i`. It would be nice to find an alternative so it can be removed from '"mandatory" dependencies
- matplotlib: not needed
- plotly: not needed

This also poses the question of handling "specific" python module dependencies (segyio, ipywidgets, ...)
An example of `pyproject.toml`:
```toml
[project]
...
dependencies = ["numpy", "pandas"]  # Core computational dependencies
...
[project.optional-dependencies]  # Can be install using pip install gstlearn[all]
common = ["matplotlib", "plotly", "scipy"]  # For test, demos, ...
segy = ["segyio"]
gui = ["ipywidgets", ...]
all = ["gstlearn[common,segy,gui]"]  # Require pip >= 21.1
all = ["matplotlib", "plotly", "scipy", "segyio", "ipywidgets", ...]  # Alternative
```
